version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: "/src/Rearch"
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: "/sample/Example"
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: "/src/Rearch.Reactor"
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: "/sample/Reactor.Example"
    schedule:
      interval: weekly
