name: Publish Release(s)

on:
  push:
    tags:
      - "*"

env:
  SolutionName: ./Rearch.Build.sln
  NuGetDirectory: ${{github.workspace}}/nuget
  NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - run: dotnet build ${env:SolutionName} --configuration Release /p:Version=${VERSION}
      - name: Create the package
        run: dotnet pack ${env:SolutionName} --configuration Release /p:Version=${VERSION} --no-build --output ${NuGetDirectory}
      - name: Publish the package to NuGet
        run: dotnet nuget push ${NuGetDirectory}/*.nupkg --api-key ${NUGET_AUTH_TOKEN} --source https://api.nuget.org/v3/index.json
