# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test

on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

env:
  SolutionName: ./Rearch.Build.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${env:SolutionName}
    - name: Build
      run: dotnet build ${env:SolutionName} --no-restore
    - name: Test
      run: dotnet test ${env:SolutionName} --no-build --verbosity normal
